### ISSUE TITLE
[Bug] Aimbot rarely shoots if auto-scope enabled

### ISSUE THREAD

**Issue by databoose** [L1nuxDotFun/spacehook#11]
I noticed an issue with auto-scope, with non scoped weapons it seems to rarely ever shoot, no matter how drastically i change hitchance, from completely off to all the way up, it just rarely shoots.

However, when i turn auto-scope off, it seems to completely fix the issue, i don't know if this is due to my own client because i haven't tested with other people, but i thought i would report this incase it is a universal issue.

**Comment by xDyln** [comment]
hmm i will check this later, thanks for this

**Comment by n0bodysec** [comment]
https://github.com/LWSS/Fuzion/pull/407
