### ISSUE TITLE
Make autoshoot respect aimkey only

### ISSUE THREAD

**Issue by rustyvans** [L1nuxDotFun/spacehook#14]
Title. Autoshoot on [keypress]

With silent aim enabled you can't always tell if your shot can connect to an enemy, especially with autowall enabled, so you either have to enable autoshoot or hold down the fire button and hope it connects. With autoshoot toggled with a keypress you can hold it down as you please without wasting bullets and also reassured that it will only shoot at someone when it (probably) can.
Also you no longer have to manually fire when the aimbot locks onto enemy or use triggerbot (no per-weapon settings)

**Comment by xDyln** [comment]
is this an issue or a feature request?

**Comment by koutsie** [comment]
Any updates?

**Comment by koutsie** [comment]
Closing; for now.
Please open up a new issue with a better, or rather a clearer explanation.
