### ISSUE TITLE
Arch build error

### ISSUE THREAD

**Issue by xeeth** [L1nuxDotFun/spacehook#15]
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/SpaceHook.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
cat: build_id: No such file or directory
mv: cannot stat 'libFuzion.so': No such file or directory

**Comment by koutsie** [comment]
Could you provide full logs?

**Comment by TuXPick** [comment]
Same I can't build it. I was able to few weeks ago without any errors.

**Comment by xDyln** [comment]
> Same I can't build it. I was able to few weeks ago without any errors.

im still wondering why i cant, its only working on debian rn, im going to fix, eta fix is 2 days.

**Comment by xDyln** [comment]
> > > Same I can't build it. I was able to few weeks ago without any errors.
> > 
> > 
> > im still wondering why i cant, its only working on debian rn, im going to fix, eta fix is 2 days.
> 
> Thanks for the hard work. This cheat is much better than Fuzion.

it really isnt. Fuzion is just the same now.

**Comment by xDyln** [comment]
Whoops didn't mean to do that.

**Comment by koutsie** [comment]
Dylan, what the fuck.
