### ISSUE TITLE
SpaceHook now crashes game after Injection!

### ISSUE THREAD

**Issue by zombojojo181** [L1nuxDotFun/spacehook#18]
Game crashes instantly after is has been injected, currently using latest version of SpaceHook. My game was just Updated earlier on today (As of Sep, 19 2019). I have not been VAC Banned.

Currently Using Linux Mint 19.1 Cinnamon

**Comment by juhssi3** [comment]
Same for me

**Comment by Aimtux68** [comment]
Cheat is now outdated and the project is dead.  You will have to update it yourself or use Fuzion instead.

**Comment by goflex** [comment]
i pushed a fix for the crashing not sure when/if they will accept it

**Comment by xDyln** [comment]
fixed i think thanks to @goflex
