### ISSUE TITLE
Is crash

### ISSUE THREAD

**Issue by froojoo** [L1nuxDotFun/spacehook#22]
Crashes after latest update. Effected Fuzion as well

**Comment by zombojojo181** [comment]
yep

**Comment by zombojojo181** [comment]
im not too sure but I manually edited it my self and updated it for it to work. It has to to do with the "IClientEntity.h" file, after that I just rebuilt it and BOOM works.

**Comment by koutsie** [comment]
interesting

**Comment by matt1tk** [comment]
@koutsie i borrowed ur site code for my site hope its ok <3

**Comment by koutsie** [comment]
nice and relevant discussion, as always.

**Comment by matt1tk** [comment]
first time i’ve ever been able to contact you bruh, messaged your steam and your tox, no answer.

**Comment by koutsie** [comment]
is fix.
also my tox changed, ill update site with new toxID in eta 15 minutes.
