### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by jackKiZhu** [L1nuxDotFun/spacehook#28]
fatal error: xdo.h: No such file or directory
  #include <xdo.h>
Please send this xdo. H, thank you!

**Comment by localplayer0** [comment]
install xdo

**Comment by localplayer0** [comment]
z

**Comment by jackKiZhu** [comment]
Where can I download XdO?

**Comment by jackKiZhu** [comment]
> install xdo

Where can I download XdO?
