### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by KaaCI05** [L1nuxDotFun/spacehook#32]
I'm trying to build but it gives me this error:
https://user-images.githubusercontent.com/33593734/71528140-d2a37580-28de-11ea-9c72-f465d5d955d9.png
I'm using manjaro btw

**Comment by orcololo** [comment]
https://github.com/L1nuxDotFun/spacehook#how-to-install-

> How to install:
> oh yeah rolling release distro support was lost cus this shit wont build for some idiotic reason lmao

**Comment by localplayer0** [comment]
you have to install xdo package.
